package org.group_gb.tg_bot.bot_state;

public enum ChatState {
    WAITING_COMMAND,
    WAITING_GEOMARK,
    WAITING_RECOMMENDATION_GEOMARK,
    WAITING_GEOMARK_NOW,
    WAITING_GEOMARK_TODAY,
    WAITING_GEOMARK_2DAYS,
    WAITING_GEOMARK_WEEK
}